version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    labels: ["type: dependencies", "area: build"]
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: ["type: dependencies", "area: ci"]
    open-pull-requests-limit: 5
